"use client";

import { motion } from "framer-motion";

const phases = [
  {
    phase: "01",
    title: "Days 1–14",
    subtitle: "Territory Activation",
    items: [
      "Deploy 202-lead prospecting table — accounts already scored and enriched",
      "Contact Lexington PD (mid-vendor-evaluation) and Louisville Metro (budget approved)",
      "Map Motorola Solutions regional rep for KY/TN co-selling",
      "Connect with existing BRINC field operators for deployment playbook knowledge transfer",
      "Build grant eligibility profiles for top 25 accounts (COPS, BSIR, FEMA BRIC, Byrne JAG)",
    ],
  },
  {
    phase: "02",
    title: "Month 1–2",
    subtitle: "Pipeline Build",
    items: [
      "Schedule meetings with P1 accounts across FL, TX, TN — prioritized by ban urgency",
      "Develop agency-specific ROI models: cost of grounded fleet vs. Guardian deployment cost minus grant coverage",
      "Build referral loop: agencies that deploy early become reference accounts for neighboring counties",
      "Attend regional law enforcement conferences with BRINC demo hardware",
      "Establish relationships with state procurement offices in target states",
    ],
  },
  {
    phase: "03",
    title: "Month 3",
    subtitle: "First Closes",
    items: [
      "Convert Tier 1 accounts with active bans and identified grant funding paths",
      "Upsell FlightDeck software on every hardware conversation — ARR is the defensible moat",
      "Propose multi-agency purchasing cooperatives to reduce per-unit cost and accelerate procurement",
      "Document first deployment wins for internal case studies and sales enablement",
      "Expand territory map based on neighboring agency interest generated by early deployments",
    ],
  },
];

export default function First90Days() {
  return (
    <section className="py-24 px-6 bg-surface/30">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-12"
        >
          <h2 className="text-xs font-mono text-text-muted tracking-[0.2em] uppercase mb-3">
            GTM Plan
          </h2>
          <p className="text-2xl sm:text-3xl md:text-4xl font-bold mb-4">
            First 90 days in territory.
          </p>
          <p className="text-text-secondary max-w-2xl">
            Not a hypothetical. The prospecting table is built, the top accounts
            are identified, and two agencies in my backyard are in active
            procurement right now.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {phases.map((phase, i) => (
            <motion.div
              key={phase.phase}
              className="rounded-lg border border-border bg-bg overflow-hidden"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.15 }}
            >
              {/* Header */}
              <div className="px-6 py-4 border-b border-border bg-surface">
                <div className="flex items-center gap-3">
                  <span className="font-mono text-2xl font-bold text-accent">
                    {phase.phase}
                  </span>
                  <div>
                    <h3 className="font-bold text-sm">{phase.title}</h3>
                    <p className="text-xs text-text-muted">{phase.subtitle}</p>
                  </div>
                </div>
              </div>

              {/* Items */}
              <div className="p-6">
                <ul className="space-y-3">
                  {phase.items.map((item, j) => (
                    <li key={j} className="flex gap-3 text-sm">
                      <span className="text-accent mt-0.5 flex-shrink-0">
                        <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                        </svg>
                      </span>
                      <span className="text-text-secondary leading-relaxed">
                        {item}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
